[package]
name = "bevy_experiments"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
bevy = { version = "0.17.3", features = ["dynamic_linking"] }
ron = "0.12.0"
serde = { version = "1.0.228", features = ["derive"] }
